### ISSUE TITLE
Error running dggrid_instance.grid_cell_polygons_for_extent()

### ISSUE THREAD

**Issue by jlguilherme** [allixender/dggrid4py#1]
Hi - thanks for this package, I am looking forward to start using it!

This is the first time I use python and, therefore, I assume this problem is probably form my side. 

After installing all packages I tried to ran the lines of code you provide to test if things are working

`import geopandas
import shapely

from dggrid4py import DGGRIDv7

# create an inital instance that knows where the dggrid tool lives, configure temp workspace and log/stdout output
dggrid_instance = DGGRIDv7(executable='../src/apps/dggrid/dggrid', working_dir='/tmp/grids', capture_logs=False, silent=False)

# global ISEA4T grid at resolution 5 into GeoDataFrame to Shapefile
gdf1 = dggrid_instance.grid_cell_polygons_for_extent('ISEA4T', 5)`

but here I'm getting the following error:
`>>> gdf1 = dggrid_instance.grid_cell_polygons_for_extent('ISEA4T', 5)
FileNotFoundError(2, 'The system cannot find the path specified')
Traceback (most recent call last):
  File "C:\Users\GUILHERME\Miniconda3\lib\site-packages\dggrid4py\dggrid_runner.py", line 493, in run
    os.chdir(self.working_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/tmp/grids'
Traceback (most recent call last):
  File "C:\Users\GUILHERME\Miniconda3\lib\site-packages\dggrid4py\dggrid_runner.py", line 493, in run
    os.chdir(self.working_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/tmp/grids'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\GUILHERME\Miniconda3\lib\site-packages\dggrid4py\dggrid_runner.py", line 802, in grid_cell_polygons_for_extent
    dggs_ops = self.dgapi_grid_gen(dggs, subset_conf, output_conf )
  File "C:\Users\GUILHERME\Miniconda3\lib\site-packages\dggrid4py\dggrid_runner.py", line 616, in dgapi_grid_gen
    result = self.run(metafile)
  File "C:\Users\GUILHERME\Miniconda3\lib\site-packages\dggrid4py\dggrid_runner.py", line 529, in run
    self.last_run_logs(repr(e))
TypeError: 'str' object is not callable
>>>`

Any suggestion on how to overcome this would be very much appreciated!

Thanks!

**Comment by birdMig** [comment]
Sorry the initial message was unformatted...

Hi - thanks for this package, I am looking forward to start using it!

This is the first time I use python and, therefore, I assume this problem is probably form my side.

After installing all packages I tried to ran the lines of code you provide to test if things are working

```
`import geopandas
import shapely

from dggrid4py import DGGRIDv7
create an inital instance that knows where the dggrid tool lives, configure temp workspace and log/stdout output

dggrid_instance = DGGRIDv7(executable='../src/apps/dggrid/dggrid', working_dir='/tmp/grids', capture_logs=False, silent=False)
global ISEA4T grid at resolution 5 into GeoDataFrame to Shapefile

gdf1 = dggrid_instance.grid_cell_polygons_for_extent('ISEA4T', 5)`
```

But here I'm getting the following error:
```
>>> gdf1 = dggrid_instance.grid_cell_polygons_for_extent('ISEA4T', 5)
FileNotFoundError(2, 'The system cannot find the path specified')
Traceback (most recent call last):
File "C:\Users\GUILHERME\Miniconda3\lib\site-packages\dggrid4py\dggrid_runner.py", line 493, in run
os.chdir(self.working_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/tmp/grids'
Traceback (most recent call last):
File "C:\Users\GUILHERME\Miniconda3\lib\site-packages\dggrid4py\dggrid_runner.py", line 493, in run
os.chdir(self.working_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/tmp/grids'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "", line 1, in
File "C:\Users\GUILHERME\Miniconda3\lib\site-packages\dggrid4py\dggrid_runner.py", line 802, in grid_cell_polygons_for_extent
dggs_ops = self.dgapi_grid_gen(dggs, subset_conf, output_conf )
File "C:\Users\GUILHERME\Miniconda3\lib\site-packages\dggrid4py\dggrid_runner.py", line 616, in dgapi_grid_gen
result = self.run(metafile)
File "C:\Users\GUILHERME\Miniconda3\lib\site-packages\dggrid4py\dggrid_runner.py", line 529, in run
self.last_run_logs(repr(e))
TypeError: 'str' object is not callable
```
Any suggestion on how to overcome this would be very much appreciated!

Thanks!

**Comment by allixender** [comment]
Hi @jlguilherme ,

sorry I dind't see this long time :-) My bad. We still haven't really added adequate documentation. Something I should really do soon.

When you create the dggrid instance here:

```python
dggrid_instance = DGGRIDv7(executable='../src/apps/dggrid/dggrid', working_dir='/tmp/grids', capture_logs=False, silent=False)
```

you see there is an option `working_dir` which in this example is set to the directory `/tmp/grids` . This working directory is need for dggrid to create temporary files when the geometries are built ... only then they are read into a Geopandas dataframe again. It looks your run failed because you didn't have this directory (I created it manully first). If you omit this option, then Python would try to allocate an arbitrary TEMP directory for working with.

Hope this helps.
Cheers,
Alex
